****************************************************************************************************
Error computing benchmark
****************************************************************************************************
Error in file(file, "rt") : cannot open the connection
Calls: read.csv -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'exreport/exreport_unknown.csv': No such file or directory
Execution halted
